### ISSUE TITLE
UDTs creation

### ISSUE THREAD

**Issue by rashtao** [azuqua/cassanknex#10]
It would be great to have a method to create User-Defined-Types:
http://docs.datastax.com/en/cql/3.1/cql/cql_reference/cqlRefcreateType.html

**Comment by rashtao** [comment]
Should be achieved with: https://github.com/azuqua/cassanknex/pull/11

**Comment by rashtao** [comment]
see https://github.com/azuqua/cassanknex/pull/11

**Comment by UnbounDev** [comment]
Continuing discussion on UDT creation integration...

The current proposed implementation has the following call signature for creating a type:
```
cassanKnex("cassanKnexy")
           .createType("myType")
           .text("textType")
           .list("listType", "text");
```

Which seems appropriate, what we're missing is a suitable signature for using that type in a `createColumnFamily` statement; since UUDT's in Cassandra require the `frozen` keyword  I'd prefer something like the following (for standard columns/sets/maps):

```
var cql = cassanKnex("ks")
    .createColumnFamilyIfNotExists("cf")
    .frozen("uudtType", "myType");
// compiles => CREATE TABLE ks.cf ( uudtType frozen <myType> ) ;

// and
    .frozenSet("uudtTypeSet", "myType");
// compiles => CREATE TABLE ks.cf ( uudtType set<frozen <myType>> ) ;

// and
    .frozenMap("uudtTypeMap", "standardType", "myType");
// compiles => CREATE TABLE ks.cf ( uudtType map<standardType, frozen <myType>> ) ;

```

**Comment by rashtao** [comment]
I agree
